@startuml
:图书管理员:as Lib
:读者:as Bor
:系统管理员:as Adm
left to right direction
rectangle 图书管理系统{
Lib -> (归还处理)
(归还处理)..>(检查图书):<<include>>
(检查图书).>(收取罚金):<<include>>
(收取罚金).>(归还处理):<< extend >>
Lib -> (借阅处理)
(续借处理)<.(借阅处理):<<include>>
(借阅处理)..>(核实身份):<<include>>
Lib --> (预约处理)
(借阅处理).>(预约处理):<<include>>
(借书)<-Bor
(还书)<-Bor
(超期罚款)..>(还书):<<extend>>
(图书预定)<--Bor
(查阅图书)<..(图书预定):<<include>>
(登录)<..(图书预定):<<include>>
(续借)..>(登录):<<extend>>
(查询借阅信息)<-Bor
(登录)<..(查询借阅信息):<<include>>

Adm --> (维护读者信息)
(维护读者信息)..>(增加读者信息):<<include>>
(维护读者信息)..>(删除和更新读者信息):<<include>>
Adm --> (维护图书)
(维护图书)..>(增加图书):<<include>>
(维护图书)..>(删除和更新图书):<<include>>
}
@enduml